### ISSUE TITLE
Target tab opened twice on middle click in dropdown item

### ISSUE THREAD

**Issue by MurzNN** [ethanliu/location-switcher-addon#11]
When I make middle click on extension dropdown item, before it opens one new tab with target url normally. But after some time (maybe after some extension update, or firefox) it starts to always open two tabs with same url after click, instead of one.

Can you reproduce this problem on your side? If yes, can fix it?

**Comment by MurzNN** [comment]
I use [Tree Style Tab](https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/) extension and one tab becomes children of current tab, second is new root tab (shown at bottom of list).

**Comment by ethanliu** [comment]
I can't reproduce the problem, although I'm using cmd-click on mac, not with a physical 3-button mouse, but I don't think it matters.
I also install Tree Style Tab for a quick test, it doesn't seems effect anything.
I'll try it on a windows machine later, see if anything different.

**Comment by MurzNN** [comment]
Thanks for testing! Seems there are conflict with some other extension. I use Linux machine too, so I'll try to reproduce it on clean FF install.

**Comment by MurzNN** [comment]
I reproduce this on clean profle in Ubuntu 19.04 with FF 68.0.1 (64-bit), here is screencast: https://imgur.com/a/sXGTVgT
_P. S. My mouse works well :) - opens only one tab via middle-click on page urls._

**Comment by MurzNN** [comment]
On single click url switch normally in current tab, without creating new tab

**Comment by MurzNN** [comment]
I have found workaround - drag needed link to tab bar via mouse, for open new tab with it :)

**Comment by ethanliu** [comment]
I finally found a 3-button mouse and tried with different profiles and different builds.

v69 with my current profile - open two tabs
v69 with new profile - open two tabs

v60ESR with current profile - some issue and unable to test
v60ESR with new profile - open one tab

v70dev with current profile - open two tabs (the actual code runs only once)
v70dev with new profile - open one tab

It might be conflicts with other plugin or the profile?, or might just happened in v69, I'm not sure.
However cmd-click all works as expected.

**Comment by ethanliu** [comment]
I have another test today, and both v69 and v70 dev-edition opens two tabs not matter with a new profile or not, strange huh?

Looks like the middle-click always opens the link in new tab or window, as least on v69 and v70.
I think the best I can do is just ignore the middle-click event, let it opens in a new tab or window by default.

**Comment by MurzNN** [comment]
>  I think the best I can do is just ignore the middle-click event, let it opens in a new tab or window by default.

Yes, I think this will be solution, so Firefox open one of new tab without extension (like regular link) second is opened already via extension code.

**Comment by MurzNN** [comment]
Fixed in last release, thanks!
