### ISSUE TITLE
Replace tab favicon by location icon

### ISSUE THREAD

**Issue by MurzNN** [ethanliu/location-switcher-addon#12]
At now each location can have individual icon - that's good! But when we have tab with different locations, they have same favicons, so not too easy to differ them. 

Good solution for this problem can be option to replace site favicon (that shown in tab) by current location icon. This feature can be enabled globally, or at per-location basis via checkbox. What do you think about this idea?

As implementation of this feature you can lookup https://github.com/muffinresearch/favicon-customizer extension, that do same thing and works well.

**Comment by ethanliu** [comment]
One thing caught me first,
only Chrome supports svg format favicon at the moment, however Chrome doens't support using svg image for toolbar, etc.

**Comment by MurzNN** [comment]
Maybe convert icons to ~~.bmp~~ .png format?

**Comment by ethanliu** [comment]
the good news is, Firefox does support svg favicon while I'm currently testing on v72 that make this possible, I'll update more information as soon as I made any progress.

**Comment by ethanliu** [comment]
Everything works well, I have update the source with alter favicon, and also get rid of dark icons.
So back to the original question, how should we implement this function?

Is it good idea to change the favicon even it's production site?
But it's kinda the idea why we need to alter the favicon for identification.

Provide a global option for alter favicon should be fine.

**Comment by ethanliu** [comment]
While I meant to submit a self-hosting beta version but missing the option again, so the v1.3.1 goes live now. alone with previous mid-click issue that I just realize that I never publish it.

**Comment by MurzNN** [comment]
Thanks for release, favicon replacement works well! Also mid-click issue fixed too!

> Is it good idea to change the favicon even it's production site?

Best solution is add separate checkbox for each item in settings "Replace tab icon", turned off by default (for not break old behavior).

**Comment by MurzNN** [comment]
https://addons.mozilla.org/en-US/firefox/addon/location-switcher-advanced/ version is published and works well, thanks! I close issue.
