### ISSUE TITLE
Provide dropdown select list when more than 1 matches to switch

### ISSUE THREAD

**Issue by MurzNN** [ethanliu/location-switcher-addon#2]
Some projects have several development sites (test1.server, test2.server, production.server) and we need to switch between all of them, so on `production.server` hostname we want to swith to test1 or test2.
At now Location Switcher do redirect to last match from rules.
Will be good to detect multiple matches and if found - provide dropdown select list with all variants. 

Example of dropdown list implementing you can see in Greasemonkey extension.

**Comment by ethanliu** [comment]
I understand completely, since I have the same kinda development environment myself. Can't remember why I dropped the idea, I'll take a look again.

**Comment by ethanliu** [comment]
![firefox-ls](https://user-images.githubusercontent.com/65704/40405292-9ac50a64-5e8e-11e8-9f3b-71ec07e43e12.png)

Should be available in a couple of days
