### ISSUE TITLE
Doesn't switch to file:/// URLs

### ISSUE THREAD

**Issue by ArsenShnurkov** [ethanliu/location-switcher-addon#3]
I am entering mapping from gh-pages to local directory, the button is present in address bar, but switching doesn't occur.

**Comment by ethanliu** [comment]
The file: URL cause a illegal URL error.
I tried tabs.executeScript with activeTab permission, and the error "Error: Access to 'file://.....' from script denied'. 

So far, I think it might be a dead end for file: URL for current purpose.


https://bugzilla.mozilla.org/show_bug.cgi?id=1266960
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/update

>     For security reasons, in Firefox, this may not be a privileged URL. So passing any of the following URLs will fail, with runtime.lastError being set to an error message:
> 
>         chrome: URLs
>         javascript: URLs
>         data: URLs
>         file: URLs (i.e., files on the filesystem. However, to use a file packaged inside the extension, see below)
>         privileged about: URLs (for example, about:config, about:addons, about:debugging, about:newtab). Non-privileged URLs (e.g., about:blank) are allowed.
>
