### ISSUE TITLE
Add icons to hosts for quickly indicate host type in Firefox panel icon

### ISSUE THREAD

**Issue by MurzNN** [ethanliu/location-switcher-addon#4]
Will be good to see icon in Firefox pane, that will indicate type of currently opened host (prod/staging/dev). 

Old http://hermann.czedik.net/projekte/switcher/ extension was use 2 icon types for indicate host type.

Can you add default icons to extension, and icon selector for each host? Thanks!

**Comment by ethanliu** [comment]
Sorry for the late response.
I always wondering how much does it benefit for identify current site from icon but URL itself, however I do notice the URL getting trimmed time to time from firefox location bar, definitely a nice bonus for the addon.

**Comment by ethanliu** [comment]
Please try the following version for the new icon options

https://www.dropbox.com/s/0mithoefqdzgkyg/location_switcher-1.1.2-fx.xpi.zip?dl=0

**Comment by MurzNN** [comment]
Thanks, works well!
